Add/rafly voting guide
PEMIRA2024/web-pemira pull request #11
Opened 2024-02-07 15:52 UTC by varelll

2024-02-10 10:36 UTC, soezyxstt commented on src/components/lokasi-voting.tsx
> +        <div className='bg-red-1 lg:pt-5 lg:px-5 w-[60vw] rounded-[2rem] overflow-clip'>
ini rounded buat di mobilenya kecilin dong

2024-02-10 10:37 UTC, soezyxstt commented on src/components/faq.tsx
> +                    <AccordionItem value={`${key}`} key={key} className="bg-yellow-500 rounded-[2rem]">
ini juga roundednya dikecilin, baik di dekstop dan mobile

2024-02-10 10:41 UTC, soezyxstt requested changes
![image](https://github.com/PEMIRA2024/web-pemira/assets/139353811/bccf3b85-83aa-43c1-af75-711860b0df21)

itu pas di mobile paddingnya kegedean, tolong kecilin

2024-02-13 12:23 UTC, raflyhangga requested changes
Responsive masalah rounded-nya udah diatur buat tiap width layar yak. Boleh dicoba lagi terus kasih feedbacknya.

2024-02-14 13:59 UTC, soezyxstt commented
> Responsive masalah rounded-nya udah diatur buat tiap width layar yak. Boleh dicoba lagi terus kasih feedbacknya.

coba resolve dulu conflictnya. sama tolong hati hati jangan sampe konflik sama yang lain

2024-02-16 15:03 UTC, raflyhangga approved these changes

2024-02-16 15:04 UTC, raflyhangga approved these changes

2024-02-18 14:04 UTC, raflyhangga approved these changes

2024-02-18 14:52 UTC, soezyxstt approved these changes

2024-02-19 06:34 UTC, merged