Add/devon prisma schema
PEMIRA2024/web-pemira pull request #8
Opened 2024-02-05 14:52 UTC by nexusprime-hak

Membuat schema prisma database yang baru. Database menggunakan postgresql dan disync ke environment Supabase.

2024-02-06 02:00 UTC, satriadhikara commented on prisma/schema.prisma
> +    name         String
tabel Mahasiswa gaperlu name ama password soalnya passwordnya token itu sendiri dan token nya gaperlu unik

2024-02-06 14:13 UTC, satriadhikara commented on prisma/schema.prisma
> +  passwordHash String @unique
passwordHash gaperlu unik

2024-02-06 14:50 UTC, satriadhikara requested changes
coba bikin ulang schema nya,  coba kalau ada dua tabel vote (k3m dan mwawm), masing2 tabelnya ada kolom pil1 2 3. isinya boleh nama calon (str) atau nomor calon (int)

**Vote**

- id
- pil 1
- pil 2
- pil 3

2024-02-07 06:10 UTC, satriadhikara commented on prisma/schema.prisma
> +model Admin {
oke Admin udah bener tp tambah id soalnya semua tabel hrs punya @id

2024-02-07 06:26 UTC, satriadhikara requested changes
- Admin
Approved **TAPI** tambahin `id` karena semua tabel wajib punya `@id` dan mending `passwordHash` nya gaperlu unik

- CalonK3M dan CalonMWAWM
Di delete aja soalnya gaperlu menyimpan info para calon

- Mahasiswa
Approved tapi kolom `name` gaperlu

- VoteK3M dan VoteMWAWM
Approved **TAPI** ganti aja jadi string deh biar lebih aman querynya dan optional jadi tambahin `?`

2024-02-07 14:41 UTC, nexusprime-hak commented
Fields sudah direvisi lagi ka

2024-02-08 01:19 UTC, satriadhikara approved these changes

2024-02-09 06:31 UTC, satriadhikara requested changes
**APPROVED ya**
oiya last itu ganti datasource db nya jadi yg awal aja


datasource db {
    provider  = "postgresql"
    url       = env("POSTGRES_PRISMA_URL") // uses connection pooling
    directUrl = env("POSTGRES_URL_NON_POOLING") // uses a direct connection
}


biar diterima vercel

2024-02-09 10:15 UTC, satriadhikara requested changes

2024-02-09 10:15 UTC, satriadhikara commented on prisma/schema.prisma
> +  id           String @id @defaukt(uuid())
ini typo ya benerin dlu

2024-02-24 06:17 UTC, satriadhikara approved these changes

2024-02-24 06:18 UTC, merged